// flow-typed signature: ec9fb0c01d47d8363ac13b49ddbe0b17
// flow-typed version: <<STUB>>/react-saga_v^0.2.6/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-saga/lib' {
  declare module.exports: any;
}

declare module 'react-saga/tests/reactSaga-tape' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-saga/lib/index' {
  declare module.exports: $Exports<'react-saga/lib'>;
}
declare module 'react-saga/lib/index.js' {
  declare module.exports: $Exports<'react-saga/lib'>;
}
declare module 'react-saga/tests/reactSaga-tape.js' {
  declare module.exports: $Exports<'react-saga/tests/reactSaga-tape'>;
}
